### ISSUE TITLE
start reader when input device connects

### ISSUE THREAD

**Issue by solidstudio** [klepthys/node-evdev#3]
Anyway to start a reader when the input device connects?

**Comment by sdumetz** [comment]
Could you provide more information on your use case? I don't know much about bluetooth readers, but if they work like a normal device, an udev rule could start the service automatically.

**Comment by solidstudio** [comment]
changed my issue description, they work like a normal device so I just need to detect when a device is connected. How do I create a udev rule to start the service? Great project btw

**Comment by sdumetz** [comment]
Thanks, don't hesitate to contribute or suggest, if you have ideas of missing features.

I'm not an expert on udev rules but I know it's possible with systemd to start a service when a device is detected. Something like this blogpost : [Proper(-ish) way to start long-running systemd service on udev event ](http://blog.fraggod.net/2012/06/16/proper-ish-way-to-start-long-running-systemd-service-on-udev-event-device-hotplug.html).

Please let me know if the service cause any problem when started like this.

**Comment by solidstudio** [comment]
used this

[https://github.com/cheery/node-udev](url)

Worked great!
