### ISSUE TITLE
multiple inputs same events

### ISSUE THREAD

**Issue by solidstudio** [klepthys/node-evdev#4]
How can is isolate an event to a specific input? I'm monitoring events on multiple inputs with the same events so need to get a handle on both the event and the input that made it.

**Comment by sdumetz** [comment]
I think the proper way for now to do it would be to create multiple readers, and give each one just 1 device to open.

You can even have an `eventEmitter` class doing something like :  like : 

```
readerFiles.forEach((file)=>{
    var reader = new EvdevReader();
    this.readers.push(reader);
    reader.open(file);
    reader.on("EV_KEY",(ev)=>{
        this.emit(Object.assign({reader:file},ev);
    });
});
```

Theoretically I think this could be done internally with little trouble, if you want to provide a PR implementing it it should be OK.

**Comment by solidstudio** [comment]
Thanks, it seems my issue is that I have 2 identical bluetooth devices that both seem to connect to the same path '/dev/input/event5' when connected separately. If I connect them at the same time the path is different. Is there another way to handle this scenario that I'm missing, sorry not much experience in this space.

**Comment by sdumetz** [comment]
Maybe use the `/dev/input/by-id` they should always be different.
