### ISSUE TITLE
index.js link on npmjs goes nowhere

### ISSUE THREAD

**Issue by raspyweather** [klepthys/node-evdev#8]
Hey,
atyour [npmjs entry]( https://www.npmjs.com/package/evdev) you link your example like that which leads nowhere
https://github.com/klepthys/node-evdev/blob/HEAD/sdumetz/blob/master/index.js

**Comment by sdumetz** [comment]
fixed in https://github.com/sdumetz/node-evdev/commit/293cf7ddeff18c8e650880adedb418a0e2de49f7

Will get updated on next release

It's because I used a relative link :/

Thanks for reporting :-)
